name: HealthCardAccessKit
options:
  bundleIdPrefix: de.gematik.ti.healthcardaccess
  deploymentTarget:
    macOS: 10.12
    iOS: 12.1
  minimumXcodeGenVersion: 2.3.0
settings:
  base:
    SWIFT_VERSION: 5.0
    ALWAYS_SEARCH_USER_PATHS: NO
    FRAMEWORK_SEARCH_PATHS: "$(inherited)"
  configs:
    Release:
      SWIFT_COMPILATION_MODE: wholemodule
    Debug:
      SWIFT_COMPILATION_MODE: incremental
targets:
  HealthCardAccessKit:
    type: framework
    platform: [macOS,iOS]
    info:
      path: Resources/HealthCardAccessKit_Info.plist
    sources:
      - Sources
    dependencies:
      - carthage: CardReaderProviderApi
      - carthage: CardReaderAccess
      - carthage: GemCommonsKit
      - carthage: ASN1Kit
      - carthage: DataKit
    scheme:
      testTargets:
        - HealthCardAccessKitTests_${platform}
      gatherCoverageData: true
  HealthCardAccessKitTests:
    type: bundle.unit-test
    platform: [macOS,iOS]
    info:
      path: Resources/HealthCardAccessKitTests_Info.plist
    sources:
      - path: Tests/HealthCardAccessKitTests
        excludes:
          - Integration
          - Util/CardSimulatorTerminalResource.swift
          - Util/HCATerminalTestCase.swift
    dependencies:
      - target: HealthCardAccessKit_${platform}
      - carthage: CardReaderProviderApi
      - carthage: CardReaderAccess
      - carthage: ObjCCommonsKit
      - carthage: Nimble
      - carthage: DataKit
buildImplicitDependencies: true
